SMODS.Sound{
    key="mega",
    path="mega.ogg",
    pitch=0.7,
    volume=0.6,
}

-- JESUS FUCKING CHRIST THE PATH NEEDS THE FILE EXTENSION (.ogg) UUUGHGHHHH NO COMMAS IN PATH PLEASE GOD OH FYUCK UGHFHGHHHHH